#!/usr/bin/ruby

basedir = File.dirname( __FILE__ )
command = ARGV.shift
filename =  File.join( basedir, "commands/generate", "#{command}.rb" )

if File.exist?( filename )
  require filename
else
  puts "Generator #{command} not found."
end
