#!/usr/bin/ruby

$:.unshift( "." )
$:.unshift( "lib" )

require 'rubygems'
require 'yaml'
require "scripts/lib/utils"

require 'ream/sources/fs'
require 'ream/blog/template_cache'
require 'ream/blog/template_processor'
require 'ream/blog/overrides/string'

include Utils::Log


module Sepulcrum
  class Build
    
    class SourceHash
      def initialize( obj )
        case obj
        when Hash then init_with_hash( obj )
        when String then init_with_hash( YAML.load( obj ) )
        end
      end

      def init_with_hash( hash )
        @root = hash[ "root" ]
        @mask = hash[ "mask" ]
        @map  = hash[ "map" ]
      end

      attr_reader :root, :mask, :map

      def wildcard
        File.join( root, mask )
      end
    end


    include Utils::Log

    def initialize
      load_template_processors
    end

    def templates
      @templates ||= cache( "templates.source" )
    end

    def pages
      @pages ||= cache( "pages.source" )
    end


  protected

    def sources_config
      @sources_config ||= Ream::Template.scan( "config/sources.tpl" )
    end

    def processors_mask
      SourceHash.
        new( sources_config[ "yaml:processors.source" ] ).wildcard
    end

    def load_template_processors
      info( "load_template_processors" )

      Dir[ processors_mask ].each do |filename|
        debug( "Template processor: #{filename}" )
        require filename unless File.directory?( filename )
      end
    end

    def expanded_sources_config
      @expanded_sources_config ||= 
        sources_config.with( Ream::Blog::TemplateProcessor )
    end

    def source( template_name )
      hash = SourceHash.
        new( expanded_sources_config[ template_name ] )
      Ream::Sources::FS.new( hash.root, hash.mask )
    end

    def cache( template_name )
      Ream::Blog::TemplateCache.new( source( template_name ) )
    end
  end
end

sb = Sepulcrum::Build.new
tc = sb.templates

sb.pages.each do |path, value|
  params = value[ 'parameters' ]
  params = {} unless params.is_a?( Hash )

  environment = value[ 'environment' ]
  blog_page = tc.fetch( *environment[ 'templates' ] )

  styles = blog_page[ 'environment' ][ "stylesheets" ].map{|s|
    s.path.map( "/stylesheets/%a.css" )
  }.map{|s| 
    "<link rel='stylesheet' href='#{s}' type='text/css' />"
  } * $/

  content = blog_page[ 'html.content', 
                  { "content" => value[ "page:content" ] } ]

  html_page = tc.fetch( 'html' )
  
  params[ "contents" ] = content
  params[ "html:stylesheets" ] = styles

  string = html_page[ "html:page", params ]
  info( "#{path} -> #{path.path.map( 'site/%p/%n.html' )}, #{string.size} bytes" )
  FileUtils.mkdir_p( path.path.map( "site/%p" ) )
  of = File.new( path.path.map( "site/%p/%n.html" ), "w" )
  of.write( string )
  of.close                    
end

debug( 'ok.' )
