--- hierarchy:about:me
- "О себе":
  - "псевдоним": kaineer
  - "языки":
    - 'русский': 'разговариваю'
    - english: 'can speak and write'
    - '日本語': 'すこし分かります'
  - "программирую":
    - "по работе":
      - "ruby+rails"
      - sql
      - html+css+js
    - "отлично владею":
      - c
      - cpp
    - "если будет нужно":
      - java
      - pascal
      - xslt
      - "name yours"
---
