--- hierarchy:about:me
- nick: kaineer
- languages:
  - 'русский': 'разговариваю'
  - english: 'can speak and write'
  - '日本語': 'すこし分かります'
- programming:
  - "at work":
    - "ruby+rails"
    - sql
    - html+css+js
  - easily:
    - c
    - cpp
  - "will code for bread":
    - xslt
    - pascal
    - "name yours"
---
